controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster


joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - imu_joint
      - left_motor_joint
      - right_motor_joint
      - battery_joint
      - controller_board_joint


wheel_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity


imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link
